// This file backs the studio's uniform Generate surface: POST /api/generate takes
// one gen.ModulePlan (a module + its staged components + typed fields) and turns
// it into real files, for EVERY framework — the fitness-review Round-2 mandate
// that generation must look and work identically whatever the stack, differing
// only in the component catalogue.
//
// It has two render paths behind one request shape:
//
//   - A framework with a whole-plan renderer (Magento today) renders the entire
//     ModulePlan at once via gen.RenderPlan and writes the OutFiles. Rendering the
//     plan as a whole is what will later let shared XML (module.xml, di.xml,
//     db_schema.xml) be merged across components instead of overwritten — the
//     staging model is already whole-plan, the merge is a later wave.
//   - Every other framework (Laravel, Django, Next, Symfony, Nest, FastAPI, …) has
//     no keel whole-plan renderer yet, so each component is generated by re-execing
//     the real `keel gen <type> <name> [--field …]` — the same argv-safe path
//     handleExec uses. The stream says so plainly, so the UI is honest about the
//     fallback while still submitting one plan.
//
// Either way the client submits the same ModulePlan; only the server's rendering
// differs. The handler is loopback-only, POST-only and session-token guarded like
// every other mutating route (see newMux + security.go), and it re-validates the
// plan server-side — a name or field that reaches the argv or a file path is
// checked by gen.ValidateName / gen.ValidateFields before anything is written.
package studio

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/coullworks/keel/internal/catalog"
	"github.com/coullworks/keel/internal/engine"
	"github.com/coullworks/keel/internal/gen"
)

// planComponentDTO is one staged component as the page posts it: a type, its
// collected scalar params (keyed by the component's GenInput names, incl. "name"),
// and the typed field list a model-shaped component carries. It maps 1:1 onto
// gen.PlanComponent so the studio, the CLI and (later) MCP speak one plan shape.
type planComponentDTO struct {
	Type   string         `json:"type"`
	Params map[string]any `json:"params,omitempty"`
	Fields []fieldDTO     `json:"fields,omitempty"`
}

// fieldDTO is one typed column in the shared fields table, in the studio's stable
// lowercase JSON shape. It carries the full attribute set (default/unique/index/
// length + Magento identity/unsigned/addToGrid) so the one table drives every
// framework's DDL, not just a nullable flag.
type fieldDTO struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Nullable  bool   `json:"nullable,omitempty"`
	Default   string `json:"default,omitempty"`
	Unique    bool   `json:"unique,omitempty"`
	Index     bool   `json:"index,omitempty"`
	Length    int    `json:"length,omitempty"`
	Identity  bool   `json:"identity,omitempty"`
	Unsigned  bool   `json:"unsigned,omitempty"`
	AddToGrid bool   `json:"addToGrid,omitempty"`
}

// toField turns a posted fieldDTO into a gen.Field (validated later by the plan).
func (d fieldDTO) toField() gen.Field {
	return gen.Field{
		Name:      strings.TrimSpace(d.Name),
		Type:      gen.FieldType(strings.TrimSpace(d.Type)),
		Nullable:  d.Nullable,
		Default:   d.Default,
		Unique:    d.Unique,
		Index:     d.Index,
		Length:    d.Length,
		Identity:  d.Identity,
		Unsigned:  d.Unsigned,
		AddToGrid: d.AddToGrid,
	}
}

// generatePlanBody is the whole POST payload: the target project directory plus
// the module plan to generate into it.
type generatePlanBody struct {
	Dir        string             `json:"dir"`
	Vendor     string             `json:"vendor"`
	Module     string             `json:"module"`
	Target     string             `json:"target"`
	Components []planComponentDTO `json:"components"`
	DryRun     bool               `json:"dryRun"`
}

// toPlan assembles the posted body into a gen.ModulePlan for framework fw. Empty
// field rows (no name) are dropped so a half-filled table row never becomes a
// bogus column; the plan's own Validate then checks names, target and fields.
func (b generatePlanBody) toPlan(fw string) gen.ModulePlan {
	comps := make([]gen.PlanComponent, 0, len(b.Components))
	for _, c := range b.Components {
		fields := make([]gen.Field, 0, len(c.Fields))
		for _, f := range c.Fields {
			if strings.TrimSpace(f.Name) == "" {
				continue
			}
			fields = append(fields, f.toField())
		}
		comps = append(comps, gen.PlanComponent{
			Type:   strings.TrimSpace(c.Type),
			Params: c.Params,
			Fields: fields,
		})
	}
	return gen.ModulePlan{
		Vendor:     strings.TrimSpace(b.Vendor),
		Module:     strings.TrimSpace(b.Module),
		Framework:  fw,
		Target:     gen.Target(strings.TrimSpace(b.Target)),
		Components: comps,
	}
}

// handleGenerate renders a whole ModulePlan into the focused project, streaming
// progress over SSE (the same envelope as handleBuild/handleExec). It resolves the
// project's framework from its manifest, then either renders the entire plan at
// once (Magento) or re-execs `keel gen` per component for frameworks with no
// whole-plan renderer, saying which path it took. Loopback-only, POST-only,
// token-guarded.
func handleGenerate(w http.ResponseWriter, r *http.Request) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}
	var body generatePlanBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	sw := &sseWriter{w: w, f: flusher}
	fail := func(msg string) { sw.emit([]byte("✗ " + msg)); emitDone(w, flusher, false, 1, msg) }

	dir, err := projectDir(body.Dir)
	if err != nil {
		fail(err.Error())
		return
	}
	m, err := engine.ReadManifest(dir)
	if err != nil {
		fail("not a keel project: " + dir)
		return
	}
	if len(body.Components) == 0 {
		fail("nothing staged: add at least one component, then Generate")
		return
	}

	// The plan generates for the framework FAMILY (a magento-mageos project is a
	// Magento project), so the module-concept check and the whole-plan renderer
	// both see the family rather than the variant.
	family := m.Framework
	if reg, err := catalog.Registry(); err == nil {
		family = frameworkFamily(reg, m.Framework)
	}
	plan := body.toPlan(family)
	if err := plan.Validate(); err != nil {
		fail(err.Error())
		return
	}

	// A framework with a keel whole-plan renderer renders the entire plan at once;
	// everything else falls back to per-component `keel gen`. Both key off the
	// family so a Mage-OS project renders as Magento.
	var genErr error
	if planRenderable(family) {
		genErr = renderPlanToDisk(sw, dir, plan)
	} else {
		genErr = execPerComponent(r.Context(), sw, dir, family, plan)
	}
	if genErr != nil {
		emitDone(w, flusher, false, exitCode(genErr), genErr.Error())
		return
	}
	emitDone(w, flusher, true, 0, "")
}

// planRenderable reports whether keel has a whole-plan file renderer for a
// framework. Only Magento today — it is the framework with no native generator, so
// keel ships templates for it and RenderPlan assembles them. Laravel drives
// artisan and the JS ecosystems have their own CLIs, so those take the per-
// component exec path.
func planRenderable(framework string) bool { return framework == "magento" }

// renderPlanToDisk renders a whole plan via gen.RenderPlan and writes the files,
// streaming one line per file. It is the uniform whole-plan path: the same
// ModulePlan the UI staged is rendered in one call, so a later wave can merge the
// shared XML each component contributes rather than overwriting per component.
func renderPlanToDisk(sw *sseWriter, dir string, plan gen.ModulePlan) error {
	files, err := gen.RenderPlan(plan)
	if err != nil {
		sw.emit([]byte("✗ " + err.Error()))
		return err
	}
	if len(files) == 0 {
		sw.emit([]byte("✗ the plan rendered no files"))
		return errors.New("the plan rendered no files")
	}
	sw.emit([]byte(fmt.Sprintf("→ generating %s (%d file%s) for %s",
		plan.Module, len(files), plural(len(files)), plan.Framework)))
	wrote := 0
	for _, f := range files {
		if err := writePlanFile(dir, f); err != nil {
			sw.emit([]byte("✗ " + err.Error()))
			return err
		}
		sw.emit([]byte("  + " + f.Path))
		wrote++
	}
	sw.emit([]byte(fmt.Sprintf("✓ wrote %d file%s", wrote, plural(wrote))))
	return nil
}

// writePlanFile writes one rendered OutFile under the project dir, creating parent
// directories. The path is confined to dir: RenderPlan derives it from the plan's
// target base and the component templates, whose vendor/module/name segments were
// validated (gen.ValidateName) before render, and the join is re-checked here so a
// crafted path can never escape the project.
func writePlanFile(dir string, f gen.OutFile) error {
	clean := filepath.Clean(f.Path)
	if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return fmt.Errorf("refusing to write outside the project: %s", f.Path)
	}
	dest := filepath.Join(dir, clean)
	if rel, err := filepath.Rel(dir, dest); err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("refusing to write outside the project: %s", f.Path)
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(clean), err)
	}
	if err := os.WriteFile(dest, []byte(f.Content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", clean, err)
	}
	return nil
}

// runGenComponent runs one `keel gen` argv inside dir, streaming to sw. It is a
// package var so a test can stand in for the real keel binary without building it
// (and without a test binary re-invoking itself with `gen …`) — the same seam idea
// as runCapture/projectDB. The real body is a trivial argv exec through the same
// ExecRunner handleExec uses: the name and fields reach the child as separate argv
// elements, never a shell line, so browser-supplied input cannot be a shell
// fragment. exe is the keel executable to run (os.Executable at call time).
var runGenComponent = func(ctx context.Context, sw *sseWriter, dir, exe string, argv []string) error {
	return engine.ExecRunner{Out: sw}.RunArgv(ctx, dir, append([]string{exe}, argv...))
}

// execPerComponent generates each staged component by re-execing the real
// `keel gen` for a framework with no keel whole-plan renderer. It is the honest
// fallback: it tells the user which path it took, then runs one `keel gen` per
// component through the runGenComponent seam.
func execPerComponent(ctx context.Context, sw *sseWriter, dir, framework string, plan gen.ModulePlan) error {
	exe, err := os.Executable()
	if err != nil {
		exe = "keel"
	}
	sw.emit([]byte(fmt.Sprintf("→ %s has no whole-plan renderer yet. Generating each component with `keel gen`", framework)))
	moduleFlag := ""
	if plan.Vendor != "" && plan.Module != "" {
		moduleFlag = plan.Vendor + "/" + plan.Module
	}
	for _, c := range plan.Components {
		argv := genArgv(c, moduleFlag)
		if argv == nil {
			sw.emit([]byte("✗ component " + c.Type + " has no name, skipped"))
			continue
		}
		sw.emit([]byte("→ keel " + strings.Join(argv, " ")))
		if err := runGenComponent(ctx, sw, dir, exe, argv); err != nil {
			sw.flushRemainder()
			sw.emit([]byte("✗ " + err.Error()))
			return err
		}
		sw.flushRemainder()
	}
	sw.emit([]byte("✓ done"))
	return nil
}

// genArgv builds the `keel gen` argv for one staged component: `gen <type> <name>`
// plus one `--field name:type,attr…` per field and `--module Vendor/Module` when
// the plan has one. It returns nil when the component has no name (nothing to
// generate). The field spec is assembled from the typed Field via fieldSpec, so
// every attribute the shared table collects reaches the CLI, not just nullable.
func genArgv(c gen.PlanComponent, moduleFlag string) []string {
	name := c.Name()
	if name == "" {
		return nil
	}
	argv := []string{"gen", c.Type, name}
	for _, f := range c.Fields {
		argv = append(argv, "--field", fieldSpec(f))
	}
	if moduleFlag != "" {
		argv = append(argv, "--module", moduleFlag)
	}
	return argv
}

// fieldSpec renders one gen.Field into the CLI `--field` grammar
// (name:type[,attr][,attr=value]…) that gen.ParseField reads back, so the full
// attribute set the studio's fields table collects survives the exec round-trip.
func fieldSpec(f gen.Field) string {
	spec := f.Name + ":" + string(f.Type)
	add := func(cond bool, attr string) {
		if cond {
			spec += "," + attr
		}
	}
	add(f.Nullable, "nullable")
	add(f.Unique, "unique")
	add(f.Index, "index")
	add(f.Identity, "identity")
	add(f.Unsigned, "unsigned")
	add(f.AddToGrid, "grid")
	if f.Default != "" {
		spec += ",default=" + f.Default
	}
	if f.Length > 0 {
		spec += fmt.Sprintf(",len=%d", f.Length)
	}
	return spec
}

// plural returns "s" for a count that is not one, for tidy log lines.
func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
